# .github/workflows/goreleaser.yml
name: GoReleaser

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # Required to create the GitHub Release.

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # This is required so GoReleaser can generate a changelog.
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5' # Should match your go.mod version

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # Pinned to v6.4.0
        with:
          # The version of GoReleaser to use.
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}