# file: .github/workflows/release.yml
name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  tag:
    name: "Create and Update Version"
    # Add a condition to the job to prevent it from running on commits made by the bot.
    if: "github.actor != 'github-actions[bot]'"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.create_tag.outputs.new_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Use the PAT to allow pushing to the protected main branch.
          token: ${{ secrets.RELEASE_PAT }}

      - name: Calculate next version (Dry Run)
        id: tag_dry_run
        uses: anothrNick/github-tag-action@e528bc2b9628971ce0e6f823f3052d1dcd9d512c # Pinned to v1.7.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          DRY_RUN: true

      - name: Update version in files
        run: |
          VERSION=${{ steps.tag_dry_run.outputs.new_tag }}
          echo "Bumping version to $VERSION"
          sed -i "s/VERSION=\".*\"/VERSION=\"$VERSION\"/" action.yml
          sed -i "s/repo-slice@v[0-9]*\.[0-9]*\.[0-9]*/repo-slice@$VERSION/" README.md

      - name: Verify version update
        run: |
          VERSION=${{ steps.tag_dry_run.outputs.new_tag }}
          echo "Verifying version in action.yml"
          grep "VERSION=\"$VERSION\"" action.yml
          echo "Verifying version in README.md"
          grep "repo-slice@$VERSION" README.md

      - name: Commit version bump
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # Pinned to v6.0.1
        with:
          commit_message: "chore(release): Bump version to ${{ steps.tag_dry_run.outputs.new_tag }}"
          
      - name: Create Tag
        id: create_tag
        uses: anothrNick/github-tag-action@e528bc2b9628971ce0e6f823f3052d1dcd9d512c # Pinned to v1.7.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          # Use the custom tag from the dry run to ensure consistency
          CUSTOM_TAG: ${{ steps.tag_dry_run.outputs.new_tag }}
  
  goreleaser:
    name: "Run GoReleaser"
    runs-on: ubuntu-latest
    needs: tag
    permissions:
      contents: write # Required to create the GitHub Release.
    steps:
      - name: Checkout repository at new tag
        uses: actions/checkout@v4
        with:
          # Check out the specific tag that was just created in the 'tag' job.
          ref: ${{ needs.tag.outputs.tag }}
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5' # Should match your go.mod version

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # Pinned to v6.0.0
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}