# file: .github/workflows/test.yml
name: Test and Lint

on:
  pull_request:
    branches:
      - main

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
          args: --timeout=3m

      - name: Run tests
        run: go test ./...